story3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3app.urls')),
]

story3app/urls.py
from django.urls import path
from . import views

app_name = "story3app"

urlpatterns = [
	path('', views.hello, name='home'),
	path('/project', views.another, name='project')
]

story3app/models.py
from django.db import models

# Create your models here.

story3app/views.py
from django.shortcuts import render

def hello(request):
	return render(request, 'hello.html')

def another(request):
	return render(request, 'another.html')

story3app/templates/another.html
{% load static %}

<html>
    <head>
        <title>
            Jsaon's Web
        </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container coming-soon">
            <h1>Coming soon!</h1>
            <br>
            <a href="{% url 'story3app:home' %}">back</a>
        </div>
    </body>
</html>

story3app/templates/hello.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial scale-1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <title>Jsaon's Web</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container navbar">
        <header>
            <div class="logo">
                <h1>Jsaon</h1>
            </div>

            <nav>
                <ul>
                    <li><a href="#about">About Me</a></li>
                    <li><a href="#hobbies">Hobbies</a></li>
                    <li><a href="{% url 'story3app:project' %}">Project</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </header>
    </div>


    <div class="container homepage">
        <div class="text">
            <h1>
                <span>Hello there.</span>
                <br>
                <div>
                    <span>My name is</span>
                    <span class="name">J</span>
                    <span class="m-left name">s</span>
                    <span class="m-left name">a</span>
                    <span class="m-left name">o</span>
                    <span class="m-left name">n</span>
                    <span class="m-left name">,</span>
                </div>
                <br>
                <span>I'm a human.</span>
                <a href="#about">Explore more</a>
            </h1>
        </div>
    </div>

    <div class="container about" id="about">
        <div class="text-about">
            <h1>
                About me
            </h1>
        </div>
        <div class="about-me-text">
            <p>I called Jsaon, and I am second-year student of Computer Science at University of Indonesia.</p>
            <p>I usually read manga everyday, and I dedicated my life for sleep.</p>
        </div>
        <div class="profile-image">
            <img src="{% static 'img/Profile.png' %}" alt="This text is shown if server fails to load image" />
        </div>
    </div>

    <div class="container hobbies" id="hobbies">
        <div class="text-hobbies">
            <h1>Hobbies</h1>
        </div>
        <div class="hobbies-info">
            <div class="hobby">
                <img src="{% static 'img/FPS Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>FPS Games</h1></div>
            </div><br>
            <div class="hobby">
                <img src="{% static 'img/Psy Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>Psychology</h1></div>
            </div><br>
            <div class="hobby">
                <img src="{% static 'img/Sleep Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>Sleep</h1></div>
            </div>
        </div>
    </div>


    <footer>
        <div class="container contact" id="contact">
            <p>Mind send me a message? Sweet!</p>
        </div>
        <div class="container arrow">
            <a href="#">
                <img src="{% static 'img/arrow.png' %}" alt="pict error" width="25">
            </a>
        </div>
        <div class="container logo">
            <span><a href="https://www.linkedin.com/in/johanes-jason-155220195/" target="_blank">
                <img src="{% static 'img/LinkedIn Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://www.instagram.com/knightrexyz/" target="_blank">
                <img src="{% static 'img/IG Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://steamcommunity.com/id/jsaonn/" target="_blank">
                <img src="{% static 'img/Steam Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://gitlab.com/Jsaonn/" target="_blank">
                <img src="{% static 'img/Gitlab Logo.png' %}" alt="pict error" width="25">
            </a></span>
        </div>
    </footer>

</body>
</html>